name: Publish Production Model

on:
  repository_dispatch:
    types: [new-production]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install wandb ultralytics onnx onnxslim

      - name: Extract artifact version info
        id: version
        run: |
          ARTIFACT="${{ github.event.client_payload.artifact_version }}"

          VERSION=$(echo "$ARTIFACT" | sed 's/.*:v/v/')
          TAG="yolo-model-${VERSION}"
          NAME="Model ${VERSION}"

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "name=$NAME" >> $GITHUB_OUTPUT

      - name: Download W&B artifact
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          python - << 'EOF'
          import wandb

          api = wandb.Api()

          artifact_path = "${{ github.event.client_payload.artifact_version }}"

          print("Fetching:", artifact_path)

          artifact = api.artifact(artifact_path)
          dir_path = artifact.download()

          print("Downloaded to:", dir_path)

          with open("artifact_path.txt", "w") as f:
              f.write(dir_path)
          EOF

      - name: Read artifact path
        id: paths
        run: echo "dir=$(cat artifact_path.txt)" >> $GITHUB_OUTPUT

      - name: Rename PyTorch model
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          cp "${{ steps.paths.outputs.dir }}/best.pt" "yolo-model-${VERSION}.pt"

      - name: Export ONNX model
        run: |
          python - << 'EOF'
          from ultralytics import YOLO

          version = "${{ steps.version.outputs.version }}"

          model = YOLO(f"yolo-model-{version}.pt")

          model.export(
              format="onnx",
              imgsz=224,
              opset=11,
              simplify=True
          )
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_PAT }}
          tag_name: ${{ steps.version.outputs.tag }}
          name: ${{ steps.version.outputs.name }}
          files: |
            yolo-model-${{ steps.version.outputs.version }}.pt
            yolo-model-${{ steps.version.outputs.version }}.onnx
